<?php

use App\Http\Controllers\AccessGroupController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\BillingPeriodController;
use App\Http\Controllers\CashController;
use App\Http\Controllers\CashMovementController;
use App\Http\Controllers\ClubRoleController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FeeAdjustmentController;
use App\Http\Controllers\FeeController;
use App\Http\Controllers\FeedController;
use App\Http\Controllers\FeedInteractionController;
use App\Http\Controllers\FeeGenerationController;
use App\Http\Controllers\InstitutionalLandingController;
use App\Http\Controllers\InstitutionalPageAdminController;
use App\Http\Controllers\MemberAccountController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\MemberMotorcycleController;
use App\Http\Controllers\MemberProfileContactsController;
use App\Http\Controllers\MemberProfileController;
use App\Http\Controllers\MemberProfileMotorcycleController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PublicProfileController;
use App\Http\Controllers\ReceiptController;
use App\Http\Controllers\RegionalContextController;
use App\Http\Controllers\RegionalController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoleAssignmentController;
use App\Http\Controllers\TableQueryController;
use App\Http\Controllers\UserProfileController;
use App\Http\Middleware\EnsureActiveUser;
use Illuminate\Support\Facades\Route;

Route::get('/', InstitutionalLandingController::class)->name('home');

Route::middleware(['auth', 'verified', EnsureActiveUser::class])->group(function () {
    Route::get('/institutional-page', [InstitutionalPageAdminController::class, 'index']);
    Route::patch('/institutional-page/draft', [InstitutionalPageAdminController::class, 'save']);
    Route::post('/institutional-page/publish', [InstitutionalPageAdminController::class, 'publish']);
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/feed', [FeedController::class, 'index'])->name('feed.index');
    Route::post('/feed/posts', [FeedController::class, 'store'])->name('feed.posts.store');
    Route::delete('/feed/posts/{post}', [FeedController::class, 'destroy'])->name('feed.posts.destroy');
    Route::post('/feed/posts/{post}/likes', [FeedInteractionController::class, 'toggleLike'])->name('feed.posts.likes');
    Route::post('/feed/posts/{post}/comments', [FeedInteractionController::class, 'storeComment'])->name('feed.posts.comments.store');
    Route::delete('/feed/comments/{comment}', [FeedInteractionController::class, 'destroyComment'])->name('feed.comments.destroy');
    Route::get('/me/profile', [MemberProfileController::class, 'edit'])->name('member-profile.edit');
    Route::patch('/me/profile', [MemberProfileController::class, 'update'])->name('member-profile.update');
    Route::post('/me/profile/avatar', [UserProfileController::class, 'uploadAvatar'])->name('user-profile.avatar.store');
    Route::delete('/me/profile/avatar', [UserProfileController::class, 'removeAvatar'])->name('user-profile.avatar.destroy');
    Route::patch('/me/profile/details', [UserProfileController::class, 'updateDetails'])->name('user-profile.details.update');
    Route::patch('/me/profile/contacts', [MemberProfileContactsController::class, 'update'])->name('member-profile.contacts');
    Route::post('/me/profile/motorcycles', [MemberProfileMotorcycleController::class, 'store'])->name('member-profile.motorcycles.store');
    Route::patch('/me/profile/motorcycles/{link}', [MemberProfileMotorcycleController::class, 'update'])->name('member-profile.motorcycles.update');
    Route::delete('/me/profile/motorcycles/{link}', [MemberProfileMotorcycleController::class, 'destroy'])->name('member-profile.motorcycles.destroy');
    Route::patch('/me/profile/membership-date', [MemberProfileController::class, 'updateMembershipDate'])->name('member-profile.membership-date');
    Route::post('/table-query', [TableQueryController::class, 'update']);
    Route::post('/admin/context/regional', [RegionalContextController::class, 'update'])->name('admin.context.regional');
    Route::get('/admin/regionals', [RegionalController::class, 'index'])->name('admin.regionals.index');
    Route::post('/admin/regionals', [RegionalController::class, 'store'])->name('admin.regionals.store');
    Route::patch('/admin/regionals/{regional}', [RegionalController::class, 'update'])->name('admin.regionals.update');
    Route::post('/admin/regionals/{regional}/toggle-status', [RegionalController::class, 'toggleStatus'])->name('admin.regionals.toggle-status');
    Route::get('/admin/users', [AdminUserController::class, 'index']);
    Route::post('/admin/users', [AdminUserController::class, 'store']);
    Route::patch('/admin/users/{user}/permissions', [AdminUserController::class, 'permissions']);
    Route::get('/access-groups', [AccessGroupController::class, 'index']);
    Route::post('/access-groups', [AccessGroupController::class, 'store']);
    Route::patch('/access-groups/{group}', [AccessGroupController::class, 'update']);
    Route::delete('/access-groups/{group}', [AccessGroupController::class, 'destroy']);
    Route::patch('/club-roles/{role}/access-group', [AccessGroupController::class, 'associateRole']);
    Route::post('/members/{member}/account', [MemberAccountController::class, 'store']);
    Route::patch('/members/{member}/account', [MemberAccountController::class, 'update']);
    Route::get('/members', [MemberController::class, 'index']);
    Route::post('/members', [MemberController::class, 'store']);
    Route::get('/members/{member}', [MemberController::class, 'show']);
    Route::get('/members/{member}/public-profile', [PublicProfileController::class, 'show'])->name('members.public-profile');
    Route::patch('/members/{member}', [MemberController::class, 'update']);
    Route::post('/members/{member}/motorcycles', [MemberMotorcycleController::class, 'store']);
    Route::patch('/member-motorcycles/{link}', [MemberMotorcycleController::class, 'update']);
    Route::get('/club-roles', [ClubRoleController::class, 'index']);
    Route::post('/club-roles', [ClubRoleController::class, 'store']);
    Route::patch('/club-roles/{role}', [ClubRoleController::class, 'update']);
    Route::post('/members/{member}/role-assignments', [RoleAssignmentController::class, 'store']);
    Route::patch('/role-assignments/{assignment}', [RoleAssignmentController::class, 'update']);
    Route::get('/billing-periods', [BillingPeriodController::class, 'index']);
    Route::post('/billing-periods', [BillingPeriodController::class, 'store']);
    Route::patch('/billing-periods/{period}', [BillingPeriodController::class, 'update']);
    Route::post('/billing-periods/{period}/generate', [FeeGenerationController::class, 'store']);
    Route::get('/fees', [FeeController::class, 'index']);
    Route::get('/fees/{fee}', [FeeController::class, 'show']);
    Route::post('/fees/{fee}/adjustments', [FeeAdjustmentController::class, 'store']);
    Route::post('/fees/{fee}/payments', [PaymentController::class, 'store']);
    Route::post('/payments/{payment}/reverse', [PaymentController::class, 'reverse']);
    Route::get('/cash', [CashController::class, 'index']);
    Route::post('/cash/movements', [CashMovementController::class, 'store']);
    Route::post('/cash/movements/{movement}/corrections', [CashMovementController::class, 'correct']);
    Route::post('/cash/movements/{movement}/reverse', [CashMovementController::class, 'reverse']);
    Route::post('/cash/movements/{movement}/receipt', [ReceiptController::class, 'store']);
    Route::get('/cash/movements/{movement}/receipt', [ReceiptController::class, 'show']);
    Route::get('/reports/fees', [ReportController::class, 'fees']);
    Route::get('/reports/fees/export', [ReportController::class, 'feesCsv']);
    Route::get('/reports/cash', [ReportController::class, 'cash']);
    Route::get('/reports/cash/export', [ReportController::class, 'cashCsv']);
    Route::get('/reports/fiscal', [ReportController::class, 'fiscal']);
    Route::get('/reports/fiscal/export', [ReportController::class, 'fiscalCsv']);
});

require __DIR__.'/settings.php';
